## Week 07

In [8]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array - Syntax: data_type array_name[block_size][row_size][column_size];

#print(x1)
#print(x2)
print(x3)

[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [11]:
print("x3 ndim: ", x3.ndim) #number dimensions
print("x3 shape:", x3.shape) # 
print("x3 size: ", x3.size)
print("dtype:", x3.dtype)
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype: int32
itemsize: 4 bytes
nbytes: 240 bytes


In [20]:
print(x1)
print(x1[3:5])
print(x1[::2])

[5 0 3 3 7 9]
[3 7]
[5 3 7]


In [28]:
print(x2)
print(x2[1,-3])

print(x2[::2, ::2])

print(x2[:, 0])
print(x2[2, :])

x2_sub = x2[::2, ::2]

print(x2_sub)
x2_sub[1,1] = 24
print(x2_sub)
print(x2)


[[ 3  5  2  4]
 [ 7  6  8  8]
 [ 1  6 24  7]]
6
[[ 3  2]
 [ 1 24]]
[3 7 1]
[ 1  6 24  7]
[[ 3  2]
 [ 1 24]]
[[ 3  2]
 [ 1 24]]
[[ 3  5  2  4]
 [ 7  6  8  8]
 [ 1  6 24  7]]


In [31]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [35]:
x = np.array([1, 2, 3])
print(x)

# row vector via reshape
x.reshape((1, 3))
# x[np.newaxis, :]
print(x)

# column vector via reshape
x.reshape((3, 1))
# x[:, np.newaxis]
print(x)


[1 2 3]
[1 2 3]
[1 2 3]


In [37]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
print(np.concatenate([x, y]))


z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[1 2 3 3 2 1]
[ 1  2  3  3  2  1 99 99 99]


In [43]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
print(np.concatenate([grid, grid]))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [44]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)


x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [54]:
x = np.arange(4)
print(x)

y = np.zeros(4)
print(y)
np.multiply(x, 5, out=y)

[0 1 2 3]
[0. 0. 0. 0.]


array([ 0.,  5., 10., 15.])

In [58]:
x = np.arange(1, 6)
print(x)
print(np.add.reduce(x))

print(np.add.accumulate(x))
print(np.min(x))


[1 2 3 4 5]
15
[ 1  3  6 10 15]
1


In [63]:
M = np.random.random((3, 4))
print(M)

M.sum()
M.mean()

[[0.66741038 0.13179786 0.7163272  0.28940609]
 [0.18319136 0.58651293 0.02010755 0.82894003]
 [0.00469548 0.67781654 0.27000797 0.73519402]]


0.42595061832995285

In [71]:
import pandas as pd

data = pd.read_csv('president_heights.csv')

#print(data)
#print(data['height(cm)'])
heights = np.array(data['height(cm)'])
print(heights)

print(f"Minimum height: {heights.min()}")
print(f"Maximum height: {heights.max()}")
print(f"Mean height: {heights.mean()}")
print(f"Standard deviation in average height: {heights.std()}")

print(f"25% height: {np.percentile(heights, 25)}")
print(f"Median height: {np.median(heights)}")
print(f"75% height: {np.percentile(heights, 75)}")


[189 170 189 163 183 171 185 168 173 183 173 173 175 178 183 193 178 173
 174 183 183 168 170 178 182 180 183 178 182 188 175 179 183 193 182 183
 177 185 188 188 182 185]
Minimum height: 163
Maximum height: 193
Mean height: 179.73809523809524
Standard deviation in average height: 6.931843442745892
25% height: 174.25
Median height: 182.0
75% height: 183.0
